version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack"
s3_bucket = "aws-data-pipeline-stack"
s3_prefix = "stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
