version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-data-pipeline-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1u13ll5ebmju0"
s3_prefix = "aws-data-pipeline-stack"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
