AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-data-pipline-lambda-cd

  data pipeline sam sample code

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  DataPollingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/data_pipeline.asl.json
      DefinitionSubstitutions:
        DataPollingFunctionArn: !GetAtt DataPollingFunctionArn.Arn
        PreprocessFunctionArn: !GetAtt PreprocessFunctionArn.Arn
        DataLoadingFunctionArn: !GetAtt DataLoadingFunctionArn.Arn
      Events:
        DailyPollingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the data polling pipeline every day
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 day)"
      Policies:
        - CloudWatchPutMetricPolicy: {}

  DataPollingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/filtered_stream/
      Handler: app.lambda_handler
      Runtime: python3.8

  PreprocessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/preprocess/
      Handler: app.lambda_handler
      Runtime: python3.8

  DataLoadingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/load_data/
      Handler: app.lambda_handler
      Runtime: python3.8


Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  DataPollingStateMachineArn:
    Description: "Data Polling State machine ARN"
    Value: !Ref DataPollingStateMachine
  DataPollingStateMachineRoleArn:
    Description: "IAM Role created for Data Pipelining State machine based on the specified SAM Policy Templates"
    Value: !GetAtt DataPollingStateMachineRole.Arn
