AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-data-pipline-lambda-cd

  data pipeline sam sample code

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: my_layer
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
      
  DataPollingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: filtered_stream
      CodeUri: functions/filtered_stream/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref MyLayer
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: data-pipeline-team3/bearer_token

  PreprocessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: preproccess
      CodeUri: functions/preprocess/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref MyLayer


  DataLoadingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: load_data
      CodeUri: functions/load_data/
      Handler: app.lambda_handler
      Runtime: python3.8  
      Layers:
        - !Ref MyLayer


  DataPollingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/data_pipeline.asl.json
      DefinitionSubstitutions:
        DataPollingFunctionArn: !GetAtt DataPollingFunction.Arn
        PreprocessFunctionArn: !GetAtt PreprocessFunction.Arn
        DataLoadingFunctionArn: !GetAtt DataLoadingFunction.Arn
      Events:
        DailyPollingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Schedule: "rate(1 day)"
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - LambdaInvokePolicy:
            FunctionName: ""



Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  DataPollingStateMachineArn:
    Description: "Data Polling State machine ARN"
    Value: !Ref DataPollingStateMachine
  DataPollingStateMachineRoleArn:
    Description: "IAM Role created for Data Pipelining State machine based on the specified SAM Policy Templates"
    Value: !GetAtt DataPollingStateMachineRole.Arn

