on:
  push:
    branches:
      - main
env: 
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # run test
      # - run: pip install -r tests/requirements.txt --user
      # - run: python -m pytest tests/unit -v

      # sam build
      - run: sam build --use-container

      # sam deploy
      - run: sam deploy 
